# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= Figaro.env.sendgrid_username %>
  email_provider_password: <%= Figaro.env.sendgrid_password %>
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: a94d28249328d3026780d7d8b097745f88e23fd7b1044f329cdd3390b4dd371cbe1025487cc2889360e998d2a02defbf884132e937a140f29b4f54cba8fb3fa5

test:
  secret_key_base: a802fdc5ebc38f7b97973aeb5b69c3f09f686ae957020a0fe30ef19d35f1662f878effe9ffca0c9d5f3ce7d40c4d826e906af830fe9a205c9967cd3c0ca596bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= Figaro.env.sendgrid_username %>
  email_provider_password: <%= Figaro.env.sendgrid_password %>
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: <%= Figaro.env.secret_key_base %>
